### ISSUE TITLE
getting certificate mismatch on server1.key

### ISSUE THREAD

**Issue by clc14** [sdoconnell/ELLIS#4]
```
root@server1 httpd]# tail ssl_error_log
[Sat Nov 17 21:36:19.023038 2018] [ssl:emerg] [pid 11648] AH02238: Unable to configure RSA server private key
[Sat Nov 17 21:36:19.023076 2018] [ssl:emerg] [pid 11648] SSL Library Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch


openssl x509 -noout -modulus -in server1.crt | openssl md5
(stdin)= 67484d56fa1f343ca7de166833740362
openssl rsa -noout -modulus -in server1.key | openssl md5 
(stdin)= 5d626a64b3d24be6a98e1c250953c476

```

**Comment by sdoconnell** [comment]
Did you perform certificate verification on the files you copied to server1, or did you verify the original generated files on the lab server (under /var/www/html/ssl/)?

**Comment by clc14** [comment]
on the lab server

**Comment by sdoconnell** [comment]
Okay, I hate openssl. I'm working on refactoring the whole cert gen section, total PITA.

**Comment by clc14** [comment]
tell me about it :) any tips on subjectAlternativeNames?

**Comment by sdoconnell** [comment]
I'm actually banging on that right now in the refactored code, so the new section will add a SAN to the cert.

**Comment by sdoconnell** [comment]
I just pushed a fix that cleans up the CA and cert generation, and properly signs the server1 certificate. It also adds a SAN of "DNS:server1.$LABDOMAIN,DNS:$LABDOMAIN" to the server1 cert. Please test with the latest version and see if that resolves your issue.

**Comment by sdoconnell** [comment]
If you want to test without running through setup again, here is my dev script for this fix. You can run it against your existing install. Mind the default variables at the top if you customized them in ELLIS when you ran it the first time.

[gencert.sh.zip](https://github.com/sdoconnell/ELLIS/files/2592632/gencert.sh.zip)

**Comment by clc14** [comment]
works great! thanks!!
